defaults:
  - agent: ddpg
  - override hydra/launcher: submitit_local


# env settings
env: SimplePointBot
obs_type: states
num_samples: 150
frame_stack: 1
action_repeat: 1
seed: 1

# experiment
experiment: exp

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${teacher}
  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${teacher}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${teacher}_${experiment}/.slurm
