defaults:
  - agent: ddpg
  - override hydra/launcher: submitit_local


# Task Settings
task: SimplePointBot_goal
env: SimplePointBot
obs_type: pixels  # [states, pixels]
frame_stack: 3
action_repeat: 1
discount: 0.99
log_freq: 100

# Module Settings
# Encoder
enc_checkpoint: False
d_latent: 32
d_obs: (3, 64, 64)
enc_init_iters: 100000
enc_kl_multiplier: 1e-6
enc_data_aug: false
enc_lr: 1e-4
enc_batch_size: 256
plot_freq: 500
checkpoint_freq: 2000
# Safe-Set
safe_set_thresh: 0.8
safe_set_thresh_mult: 0.8
safe_set_thresh_mult_iters: 5
safe_set_type: bellman  # bellman or bc
safe_set_batch_size: 256
safe_set_bellman_coef: 0.9
safe_set_bellman_reduction: max  # add or max
safe_set_n_models: 5
safe_set_init_iters: 10

# Misc Settings
seed: 1
device: cuda
use_tb: False
use_wandb: False
# Experiment
experiment: exp
