defaults:
  - agent: ddpg
  - override hydra/launcher: submitit_local

# mode
reward_free: true
# task settings
domain: SimplePointBot # primal task will be inferred in runtime
obs_type: states # [states, pixels]
frame_stack: 1 # only works if obs_type=pixels
action_repeat: 1 # set to 2 for pixels

# smm reward params
state_ent_coef: 1.0
latent_ent_coef: 1.0
latent_cond_ent_coef: 1.0
reward_scaling: 1.0

skill_dim: 4
discount: 0.99
plot: false
# train settings
num_train_frames: 20000100
num_seed_frames: 100000
random_start: false
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
snapshots: [10000, 50000, 100000, 500000, 1000000, 1500000, 2000000, 3000000, 4000000, 5000000, 6000000, 7000000, 8000000, 9000000, 10000000, 11000000, 12000000, 13000000, 14000000, 15000000, 16000000, 17000000, 18000000, 19000000, 20000000]
snapshot_dir: ../../../data/models/${obs_type}/${domain}/${agent.name}/${skill_dim}/${seed}
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
batch_size: ${agent.batch_size}
nstep: ${agent.nstep}
update_encoder: true # should always be true for pre-training
# misc
seed: 5
device: cuda
save_video: true
save_train_video: false
use_tb: false
use_wandb: true
# experiment
experiment: exp


hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}
  sweep:
    dir: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp_sweep/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}/.slurm
