defaults:
  - _self_
  - agent: sac
  - override hydra/launcher: submitit_local

# algo params
domain: SimplePointBot # primal task will be inferred in runtime
obs_type: states # [states, pixels]
discount: 0.99
frame_stack: 1
action_repeat: 1

# train settings
num_train_frames: 4000000
num_seed_frames: 10000
random_start: false
# eval
eval_every_frames: 10000
num_eval_episodes: 10
save_video: true

# exposed sac params
alpha: 0.1

# save snapshots
snapshots: [10000, 50000, 100000, 200000, 300000, 400000, 500000, 600000, 700000, 800000, 900000, 1000000, 1100000, 1200000, 1300000, 1400000, 1500000, 1600000, 1700000, 1800000, 1900000, 2000000, 2100000, 2200000, 2300000, 2400000, 2500000, 2600000, 2700000, 2800000, 2900000, 3000000, 3100000, 3200000, 3300000, 3400000, 3500000, 3600000, 3700000, 3800000, 3900000, 4000000]
snapshot_dir: ../../../data/models/${obs_type}/${domain}/${agent.name}/${seed}

# replay_buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
batch_size: ${agent.batch_size}
nstep: ${agent.nstep}

# misc
seed: 5
device: cuda
log_dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}/${seed}
use_tb: false
use_wandb: true

# experiment
experiment: exp

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}/${seed}
