# @package agent
_target_: agents.unsupervised_learning.DIAYNAgent
name: diayn

# DIAYN params
update_skill_every_step: 50
skill_dim: ${skill_dim}
diayn_scale: 1.0

# SAC params
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-3
hidden_dim: 64
gamma: 0.99
tau: 0.005
alpha: 0.1
target_step_interval: 1
automatic_entropy_tuning: false
update_every_steps: 1
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ???
batch_size: 256
init_critic: true
nstep: 3
update_encoder: ${update_encoder}
skill_type: discrete