# @package agent
_target_: agents.unsupervised_learning.SACAgent
name: sac
obs_type: ???
obs_shape: ???
action_shape: ???
device: ${device}
lr: 1e-4
hidden_dim: 64
gamma: 0.99
tau: 0.005
alpha: ${alpha}
target_step_interval: 1
automatic_entropy_tuning: False
update_every_steps: 1
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ???
batch_size: 256
init_critic: true
reward_free: false
nstep: 3